// swift-tools-version: 6.0

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "SwiftChallenge25",
    platforms: [
        .iOS("26.0")
    ],
    products: [
        .iOSApplication(
            name: "SwiftChallenge25",
            targets: ["AppModule"],
            bundleIdentifier: "academy.SwiftChallenge25",
            teamIdentifier: "M6V5WGN23W",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .weights),
            accentColor: .presetColor(.teal),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            appCategory: .games
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: ".",
            resources: [
                     .process("Resources")
              ]
        )
    ],
    swiftLanguageVersions: [.version("6")]
)
